name: CI

on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.0
          profile: minimal

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Install solc
        run: (hash svm 2>/dev/null || cargo install svm-rs@0.5.4) && svm install 0.8.21 && solc --version

      - name: Run test
        run: cargo test --workspace --all-features --all-targets -- --nocapture

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.0
          profile: minimal
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings
